package com.artspacepost.feed.archive;

import io.quarkus.hibernate.reactive.panache.PanacheRepository;
import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
class ArchiveRepository implements PanacheRepository<Archive> {
  // This class will be automatically generated by quarkus engine
}
